In [ ]:
import pandas as pd
import psycopg2
from sqlalchemy import create_engine

In [ ]:
engine = create_engine("postgres+psycopg2://root:password@db-inst-on-aws.c6vgzbne0svz.us-east-1.rds.amazonaws.com:5432")
engine

Engine(postgres+psycopg2://root:***@db-inst-on-aws.c6vgzbne0svz.us-east-1.rds.amazonaws.com:5432)

In [ ]:
crashes_df = pd.read_csv("https://data-bootcamp-seifer.s3.us-east-2.amazonaws.com/US_Accidents_June20.csv");
crashes_df.head()

    ID    Source    TMC  ...  Civil_Twilight Nautical_Twilight Astronomical_Twilight
0  A-1  MapQuest  201.0  ...           Night             Night                 Night
1  A-2  MapQuest  201.0  ...           Night             Night                   Day
2  A-3  MapQuest  201.0  ...           Night               Day                   Day
3  A-4  MapQuest  201.0  ...             Day               Day                   Day
4  A-5  MapQuest  201.0  ...             Day               Day                   Day

[5 rows x 49 columns]

In [ ]:
crashes_df.columns

Index(['ID', 'Source', 'TMC', 'Severity', 'Start_Time', 'End_Time',
       'Start_Lat', 'Start_Lng', 'End_Lat', 'End_Lng', 'Distance(mi)',
       'Description', 'Number', 'Street', 'Side', 'City', 'County', 'State',
       'Zipcode', 'Country', 'Timezone', 'Airport_Code', 'Weather_Timestamp',
       'Temperature(F)', 'Wind_Chill(F)', 'Humidity(%)', 'Pressure(in)',
       'Visibility(mi)', 'Wind_Direction', 'Wind_Speed(mph)',
       'Precipitation(in)', 'Weather_Condition', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop',
       'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'],
      dtype='object')

In [ ]:
crashes_df.columns = ['id', 'source', 'tmc', 'severity', 'start_time', 'end_time', 
                      'start_lat', 'start_lng', 'end_lat', 'end_lng', 'distance_mi', 
                      'description', 'number', 'street', 'side', 'city', 'county', 'state',
                      'zipcode', 'country', 'timezone', 'airport_code', 'weather_timestamp', 
                      'temperature_f', 'wind_chill_f', 'humidity_pct', 'pressure_in', 
                      'visibility_mi', 'wind_direction', 'wind_speed_mph', 
                      'precipitation_in', 'weather_condition', 'amenity', 'bump', 'crossing', 
                      'give_way', 'junction', 'no_exit', 'railway', 'roundabout', 'station', 
                      'stop', 'traffic_calming', 'traffic_signal', 'turning_loop', 
                      'sunrise_sunset', 'civil_twilight', 'nautical_twilight', 
                      'astronomical_twilight']
crashes_df.head()

    id    source    tmc  ...  civil_twilight nautical_twilight astronomical_twilight
0  A-1  MapQuest  201.0  ...           Night             Night                 Night
1  A-2  MapQuest  201.0  ...           Night             Night                   Day
2  A-3  MapQuest  201.0  ...           Night               Day                   Day
3  A-4  MapQuest  201.0  ...             Day               Day                   Day
4  A-5  MapQuest  201.0  ...             Day               Day                   Day

[5 rows x 49 columns]

In [ ]:
engine = create_engine('postgres+psycopg2://root:password@db-inst-on-aws.c6vgzbne0svz.us-east-1.rds.amazonaws.com:5432/db_on_aws')
#engine = psycopg2.connect(
#    database="db_on_aws",
#    user="root",
#    password="password",
#    host="db-inst-on-aws.c6vgzbne0svz.us-east-1.rds.amazonaws.com",
#    port='5432'
#)
engine

Engine(postgres+psycopg2://root:***@db-inst-on-aws.c6vgzbne0svz.us-east-1.rds.amazonaws.com:5432/db_on_aws)

In [ ]:

crashes_df.count()

id                       3513617
source                   3513617
tmc                      2478818
severity                 3513617
start_time               3513617
end_time                 3513617
start_lat                3513617
start_lng                3513617
end_lat                  1034799
end_lng                  1034799
distance_mi              3513617
description              3513616
number                   1250753
street                   3513617
side                     3513617
city                     3513505
county                   3513617
state                    3513617
zipcode                  3512548
country                  3513617
timezone                 3509737
airport_code             3506859
weather_timestamp        3470294
temperature_f            3447885
wind_chill_f             1645368
humidity_pct             3443930
pressure_in              3457735
visibility_mi            3437761
wind_direction           3454743
wind_speed_mph           3059008
precipitation_in         1487743
weather_condition        3437479
amenity                  3513617
bump                     3513617
crossing                 3513617
give_way                 3513617
junction                 3513617
no_exit                  3513617
railway                  3513617
roundabout               3513617
station                  3513617
stop                     3513617
traffic_calming          3513617
traffic_signal           3513617
turning_loop             3513617
sunrise_sunset           3513502
civil_twilight           3513502
nautical_twilight        3513502
astronomical_twilight    3513502
dtype: int64

In [ ]:
crashes_df.to_sql('crashes', con=engine, if_exists='replace', index='false')

NameError: ignored